name: nexus_app
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  speech_to_text: ^6.6.0
  audioplayers: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true