name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./frontend/mobile

      - name: Build APK
        run: |
          cp -r android ../../android
          flutter build apk --release
        working-directory: ./frontend/mobile

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nexus-ultimate-apk
          path: ./frontend/mobile/build/app/outputs/flutter-apk/app-release.apk


